### ISSUE TITLE
How about aut-ce?

### ISSUE THREAD

**Issue by MSadeghzadehG** [MatinTavakoli/Linear-Algebra#1]
How about to add this repository to [aut-ce](https://github.com/aut-ce)?

**Comment by MatinTavakoli** [comment]
sure thing!
https://github.com/MatinTavakoli/Linear-Algebra

**Comment by MatinTavakoli** [comment]
I put the README file as you wanted.
note that it will be updated because we haven't made slides for Chapter 7.
if there is anything else I can do, let me know:)
